sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t doganvolkan80/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true doganvolkan80/docker-react npm run test


deploy: 
  provider: elasticbeantalk 
  region: "eu-central-1"
  app: "docker-react-volkan"
  env: "Dockerreactvolkan-env"
  bucket_name: "elasticbeanstalk-eu-central-1-558229455194"
  bucket_path: "docker-react-volkan"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
