sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t doganvolkan80/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true doganvolkan80/docker-react npm run test

